### ISSUE TITLE
채팅에 레벨 띄우기

### ISSUE THREAD

**Issue by JiwonPaeng** [JiwonPaeng/minecraft-plugin#3]
플레이어 채팅 인터셉트해서 전체 카테고리 레벨 합산한 레벨 띄우기
스타일 변경 기능 옮겨올지 여부도 결정 필요

**Comment by mmiimin** [comment]
스타일 없이 브실골플다루 방식으로 쭉 가도 될 듯
어차피 보니까 가장 높은 레벨 스타일만 끼더라
